table_users = """
    CREATE TABLE USERS(
        EMAIL TEXT PRIMARY KEY,
        HOTEN TEXT,
        NGAYSINH TEXT,
        SDT TEXT,
        DIACHI TEXT,
        PASSPHRASE TEXT,
        MA_KHOI_PHUC TEXT,
        IS_BLOCK INTEGER,
        ROLE TEXT,
        THOI_HAN_BLOCK TEXT
    )
"""

table_user_keys = """
    CREATE TABLE USER_KEYS(
        EMAIL TEXT PRIMARY KEY,
        PUBLIC_KEY TEXT NOT NULL,
        PRIVATE_KEY_PASSWORD TEXT NOT NULL,
        PRIVATE_KEY_RECOVERY TEXT NOT NULL,
        NGAY_TAO TEXT,
        THOI_HAN INTEGER,
        LEN_KEY INTEGER,
        FOREIGN KEY (EMAIL) REFERENCES USERS(EMAIL)
    )
"""

table_email_public_keys = """
    CREATE TABLE EMAIL_PUBLIC_KEYS (
        EMAIL_MANAGER TEXT,
        EMAIL TEXT, 
        PUBLIC_KEY TEXT,
        NGAY_TAO TEXT,
        THOI_HAN INTEGER,
        PRIMARY KEY (EMAIL_MANAGER, EMAIL),
        FOREIGN KEY (EMAIL_MANAGER) REFERENCES USERS(EMAIL),
        FOREIGN KEY (EMAIL) REFERENCES USERS(EMAIL)
    )
"""